services:
  # Express 后端 Web 服务
  - type: web
    name: qb-music-api
    env: node
    region: singapore
    buildCommand: npm install
    startCommand: node index.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true